AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  SwiftLambdaApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev

  SwiftLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.hello
      Runtime: provided
      Timeout: 300
      CodeUri: s3://swift-lambda-template/swiftLambda.zip
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: POST
            RestApiId:
              Ref: SwiftLambdaApiGateway
